### ISSUE TITLE
PRACTICA PLANIFICACION DE RECURSOS

### ISSUE THREAD

**Issue by MaGuadalupeQuiroz** [SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-gestion-de-proyecto#1]
[PRACTICA PLANIFICACION DE RECURSOS.pdf](https://github.com/SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-gestion-de-proyecto/files/7572664/PRACTICA.PLANIFICACION.DE.RECURSOS.pdf)

**Comment by Jaimer117** [comment]
calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
