### ISSUE TITLE
Gestión de riesgo

### ISSUE THREAD

**Issue by MaGuadalupeQuiroz** [SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-gestion-de-proyecto#2]
[GESTIÓN DE RIESGOS.pdf](https://github.com/SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-gestion-de-proyecto/files/7572589/GESTION.DE.RIESGOS.pdf)

**Comment by EDITH-R** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
